name: CI

on:
  push:
    branches: [ master ]

jobs:
  Build-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt-get install libudev-dev libusb-1.0-0-dev libfox-1.6-dev libgtest-dev libgmock-dev
      - name: Build
        run: |
          mkdir build && cd build
          cmake -Dusbrelaymodule_BUILD_UTESTS=on -Dusbrelaymodule_BUILD_CTESTS=on ..
          make
      - name: Run Unit Tests
        run: |
          build/app-cli/tests/unit/AppCliUnitTests
      - name: Run Component Tests
        run: |
          build/libusbrelaymodule/tests/component/hidapi/GetAnyHidDeviceInfoTest
      - name: Run getrelay
        run: |
          build/app-cli/getrelay
          build/app-cli/getrelay -v
          build/app-cli/getrelay -h
      - name: Run setrelay
        run: |
          build/app-cli/setrelay

  Build-on-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          mkdir build && cd build
          cmake -G "Visual Studio 17 2022" -A Win32 -Dusbrelaymodule_BUILD_CTESTS=on .. 
          cmake --build . --config Release
      - name: Copy dll
        run: |
          cp external/hidapi/windows/Release/hidapi.dll build/app-cli/Release/
          cp external/hidapi/windows/Release/hidapi.dll build/libusbrelaymodule/tests/component/hidapi/Release/
          cp build/libusbrelaymodule/Release/usbrelaymodule.dll build/app-cli/Release/     
      - name: Run Component Tests
        run: |
          build/libusbrelaymodule/tests/component/hidapi/Release/GetAnyHidDeviceInfoTest.exe
      - name: Run getrelay
        run: |
          build/app-cli/Release/getrelay.exe
          build/app-cli/Release/getrelay.exe -v
          build/app-cli/Release/getrelay.exe -h
      - name: Run setrelay
        run: |
          build/app-cli/Release/setrelay.exe
