name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  Build-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libgtest-dev libgmock-dev libwxgtk3.0-gtk3-dev
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make
      - name: Build with Tests
        run: |
          cd build && rm -rf *
          cmake -Dusbrelaymodule_BUILD_GUI=ON -Dusbrelaymodule_BUILD_UTESTS=ON -Dusbrelaymodule_BUILD_CTESTS=ON ..
          make
      - name: Run Unit Tests
        run: |
          build/libusbrelaymodule/tests/unit/libusbrelaymodule-unit-tests --gtest_repeat=10
          build/app-cli/tests/unit/app-cli-unit-tests --gtest_repeat=10
          build/app-gui/tests/unit/app-gui-unit-tests --gtest_repeat=10
      - name: Run Component Tests
        run: |
          build/libusbrelaymodule/tests/component/hidapi/GetAnyHidDeviceInfoTest
      - name: Run CLI APP getrelay
        run: |
          build/app-cli/getrelay
          build/app-cli/getrelay -v
          build/app-cli/getrelay -h
      - name: Run CLI APP setrelay
        run: |
          build/app-cli/setrelay -v
          build/app-cli/setrelay -h
      - name: Build Portable
        run: |
          tools/build-portable-linux.sh
      - name: Run Portable CLI APP getrelay
        run: |
          build/portable/getrelay
          build/portable/getrelay -v
          build/portable/getrelay -h
      - name: Run Portable APP setrelay
        run: |
          build/portable/setrelay -v
          build/portable/setrelay -h
      - name: Build Portable Simu and GUI
        run: |
          tools/build-portable-linux.sh simu gui
      - name: Run Portable Simu CLI APP
        run: |
          build/portable/getrelay
          build/portable/setrelay R2_2=1
          build/portable/getrelay

  Build-on-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build with Component Tests
        run: |
          mkdir build && cd build
          cmake -G "Visual Studio 17 2022" -Dusbrelaymodule_BUILD_CTESTS=on ..
          cmake --build . --config Release
      - name: Copy dll
        run: |
          cp build/external/hidapi/src/windows/Release/hidapi.dll build/app-cli/Release/
          cp build/external/hidapi/src/windows/Release/hidapi.dll build/libusbrelaymodule/tests/component/hidapi/Release/
          cp build/libusbrelaymodule/Release/libusbrelaymodule.dll build/app-cli/Release/
      - name: Run Component Tests
        run: |
          build/libusbrelaymodule/tests/component/hidapi/Release/GetAnyHidDeviceInfoTest.exe
      - name: Run getrelay
        run: |
          build/app-cli/Release/getrelay.exe
          build/app-cli/Release/getrelay.exe -v
          build/app-cli/Release/getrelay.exe -h
      - name: Run setrelay
        run: |
          build/app-cli/Release/setrelay.exe -v
          build/app-cli/Release/setrelay.exe -h
      - name: Build Portable
        run: |
          tools/build-portable-windows.bat
      - name: Run Portable CLI APP getrelay
        run: |
          build/portable/getrelay.exe
          build/portable/getrelay.exe -v
          build/portable/getrelay.exe -h
      - name: Run Portable APP setrelay
        run: |
          build/portable/setrelay.exe -v
          build/portable/setrelay.exe -h
      - name: Build Portable Simu and GUI
        run: |
          tools/build-portable-windows.bat simu gui
      - name: Run Portable Simu CLI APP
        run: |
          build/portable/getrelay.exe
          build/portable/setrelay.exe R2_2=1
          build/portable/getrelay.exe
