name: CI

on:
  push:
    branches: [ master ]

jobs:
  Build-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          mkdir build && cd build
          cmake -Dnrelay_BUILD_CTESTS=on ..
          make
      - name: Run
        run: |
          build/src/getrelay
          build/src/setrelay
          build/tests/component/hidapi/GetRelayInfoTest

  Build-on-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          mkdir build && cd build
          cmake -G "Visual Studio 17 2022" -A x64 -Dnrelay_BUILD_CTESTS=on .. 
          cmake --build . --config Release
      - name: Run 
        run: |
          ./build/src/Release/getrelay.exe
          ./build/src/Release/setrelay.exe