name: CI

on:
  push:
    branches: [ master ]

jobs:
  Build-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt-get install libudev-dev libusb-1.0-0-dev libfox-1.6-dev  
      - name: Build
        run: |
          mkdir build && cd build
          cmake -Dnrelay_BUILD_CTESTS=on ..
          make
      - name: Run
        run: |
          build/src/getrelay
          build/src/setrelay
          build/tests/component/hidapi/GetAnyHidDeviceInfoTest

  Build-on-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          mkdir build && cd build
          cmake -G "Visual Studio 17 2022" -A Win32 -Dnrelay_BUILD_CTESTS=on .. 
          cmake --build . --config Release
      - name: Run 
        run: |
          build/src/Release/getrelay.exe
          build/src/Release/setrelay.exe
          build/tests/component/hidapi/Release/GetAnyHidDeviceInfoTest.exe
